server:
  port: 8999

  eureka:
    instance:
      hostname: localhost


spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
          -id: Book-Client
          uri: lb://Book-Client
          predicates:
                -path=/book/**